# Generated by Django 6.0.6 on 2026-06-10 12:08

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='تایتل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.CharField(max_length=250, verbose_name='اسلاگ')),
                ('publish', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DF', max_length=2, verbose_name='وضعیت')),
                ('study', models.PositiveIntegerField(verbose_name='زمان مطالعه')),
                ('category', models.CharField(choices=[('برنامه نویسی', 'برنامه نویسی'), ('تکنولوژی', 'تکنولوژی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بازی', 'بازی'), ('سایر', 'سایر')], default='سایر', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx')],
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
