# Generated by Django 6.0.6 on 2026-06-11 15:56

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('برنامه نویسی', 'برنامه نویسی'), ('تکنولوژی', 'تکنولوژی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بازی', 'بازی'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='تایتل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ['-create'],
                'indexes': [models.Index(fields=['-create'], name='blog_image_create_7fc02e_idx')],
            },
        ),
    ]
