# Generated by Django 6.0.6 on 2026-06-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_image_description_alter_image_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['create'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='blog_image_create_7fc02e_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['create'], name='blog_image_create_c3c427_idx'),
        ),
    ]
