# Generated by Django 6.0.6 on 2026-08-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
    ]
