# Generated by Django 6.0.6 on 2026-07-04 23:43

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='تایتل')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(upload_to='images/ticket/', verbose_name='تصویر')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'تصویر تیکت',
                'verbose_name_plural': 'تصاویر تیکت',
                'ordering': ['create'],
                'indexes': [models.Index(fields=['create'], name='blog_ticket_create_22fb40_idx')],
            },
        ),
    ]
