# Generated by Django 6.0.6 on 2026-07-06 07:00

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ticketimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
